services:
  manillen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manillen
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - /volume1/manillen_data:/app/data
